//! SQL lexical tokens and keywords.
//!
//! This module defines the `Keyword` and `Token` enums. It covers all standard SQL
//! syntax keywords supported by Basalt (e.g. SELECT, WHERE, LIMIT) as well as
//! literal strings, numbers, binary operators, and structural syntax tokens.

use std::fmt;

/// Supported keywords in the Basalt SQL query engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Keyword {
    Select,
    From,
    Where,
    OrderBy,
    Group,
    By,
    Having,
    Limit,
    Offset,
    As,
    And,
    Or,
    Not,
    Null,
    Is,
    True,
    False,
    Asc,
    Desc,
    Cast,
}

impl Keyword {
    /// Tries to parse a case-insensitive string slice into a `Keyword`.
    pub fn lookup(s: &str) -> Option<Self> {
        match s.to_ascii_lowercase().as_str() {
            "select" => Some(Keyword::Select),
            "from" => Some(Keyword::From),
            "where" => Some(Keyword::Where),
            "orderby" | "order_by" => Some(Keyword::OrderBy),
            "group" => Some(Keyword::Group),
            "by" => Some(Keyword::By),
            "having" => Some(Keyword::Having),
            "limit" => Some(Keyword::Limit),
            "offset" => Some(Keyword::Offset),
            "as" => Some(Keyword::As),
            "and" => Some(Keyword::And),
            "or" => Some(Keyword::Or),
            "not" => Some(Keyword::Not),
            "null" => Some(Keyword::Null),
            "is" => Some(Keyword::Is),
            "true" => Some(Keyword::True),
            "false" => Some(Keyword::False),
            "asc" => Some(Keyword::Asc),
            "desc" => Some(Keyword::Desc),
            "cast" => Some(Keyword::Cast),
            _ => None,
        }
    }

    /// Returns the uppercase SQL display name of the keyword.
    pub fn name(&self) -> &'static str {
        match self {
            Keyword::Select => "SELECT",
            Keyword::From => "FROM",
            Keyword::Where => "WHERE",
            Keyword::OrderBy => "ORDER BY",
            Keyword::Group => "GROUP",
            Keyword::By => "BY",
            Keyword::Having => "HAVING",
            Keyword::Limit => "LIMIT",
            Keyword::Offset => "OFFSET",
            Keyword::As => "AS",
            Keyword::And => "AND",
            Keyword::Or => "OR",
            Keyword::Not => "NOT",
            Keyword::Null => "NULL",
            Keyword::Is => "IS",
            Keyword::True => "TRUE",
            Keyword::False => "FALSE",
            Keyword::Asc => "ASC",
            Keyword::Desc => "DESC",
            Keyword::Cast => "CAST",
        }
    }
}

impl fmt::Display for Keyword {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}

/// Token representations generated by the Lexer.
#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    /// A parsed SQL keyword.
    Keyword(Keyword),
    /// An identifier name (e.g. column name or table name).
    Identifier(String),
    /// A raw numeric literal text (both integers and floats are stored as strings).
    /// The parser will decide whether to parse as integer or float.
    Number(String),
    /// A string literal.
    String(String),

    // Arithmetic operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,

    // Relational comparison operators
    Eq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,

    // Punctuation and structural symbols
    LParen,
    RParen,
    Comma,
    Semicolon,
    Dot,

    // End-of-file marker
    Eof,
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Token::Keyword(kw) => write!(f, "{kw}"),
            Token::Identifier(s) => write!(f, "{s}"),
            Token::Number(s) => write!(f, "{s}"),
            Token::String(s) => write!(f, "'{}'", s.replace('\'', "''")),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Star => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Percent => write!(f, "%"),
            Token::Eq => write!(f, "="),
            Token::NotEq => write!(f, "<>"),
            Token::Lt => write!(f, "<"),
            Token::LtEq => write!(f, "<="),
            Token::Gt => write!(f, ">"),
            Token::GtEq => write!(f, ">="),
            Token::LParen => write!(f, "("),
            Token::RParen => write!(f, ")"),
            Token::Comma => write!(f, ","),
            Token::Semicolon => write!(f, ";"),
            Token::Dot => write!(f, "."),
            Token::Eof => write!(f, "EOF"),
        }
    }
}
